// כל מחרוזות הממשק. הומור על המשחק והשחקנים — אף פעם לא על מפלגה או פוליטיקאי.

export const BONUS = [
  { key: "b1", text: "אחוז ההצבעה יעבור 70%?" },
  { key: "b2", text: "מפלגה כלשהי תיפול על אחוז החסימה בפחות מ-0.3%?" },
  { key: "b3", text: "הליכוד תקבל יותר מנדטים מביחד?" },
  { key: "b4", text: "מדגמי 22:00 יטעו במפלגה כלשהי ב-3 מנדטים או יותר?" },
  { key: "b5", text: "ייכנסו לכנסת 12 מפלגות או יותר?" },
] as const;

export const BONUS_KEYS = BONUS.map((b) => b.key) as string[];

const fill = (s: string, vars: Record<string, string | number>) =>
  s.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ""));

export const COPY = {
  title: "ליל המדגמים",
  brandA: "ליל",
  brandB: "המדגמים",
  footer: "נבנה ע״י נורית תמם",
  live: "LIVE",
  liveSub: "ליל הבחירות 2026",
  tickerLabel: "מבזק",
  ticker: [
    "ההימורים גלויים לכל חברי הקבוצה — זה חלק מהכיף",
    "120 מנדטים בדיוק. לא 119, לא 121",
    "הפתק נסגר ב-27.10 — אחרי זה רק מחכים",
    "ניחוש בול על מפלגה = 10 נקודות",
    "בליל הבחירות הדירוג מתעדכן כל דקה",
    "פותחים קבוצה לחברים, למשפחה או לעבודה — וכל אחד מנחש",
    "נביא/ת הקלפי עוד לא נקבע/ה",
  ],
  subtitle: "משחק ניחושים חברתי לבחירות לכנסת ה-26",
  joinButton: "כניסה",
  joinNameLabel: "שם משתמש",
  joinNameHint: "שם פרטי, כינוי או שם עם אות — כל עוד הוא ייחודי",
  pinLabel: "קוד אישי (4 ספרות)",
  pinHintNew: "בוחרים קוד בכניסה הראשונה, ונכנסים איתו מכל מכשיר.",
  createButton: "יצירת משתמש חדש",
  notFound: (name: string) => `אין עדיין משתמש בשם "${name}". ליצור אותו עם הקוד שהקלדת?`,
  badPin: (left: number) => `הקוד לא נכון. נשארו ${left} ניסיונות.`,
  locked15: "יותר מדי ניסיונות. נסו שוב בעוד 15 דקות.",
  weakPin: "הקוד קל מדי לניחוש. בחרו 4 ספרות אחרות.",
  pinFormat: "הקוד צריך להיות 4 ספרות.",
  nameTaken: "השם הזה תפוס. נסו להוסיף אות או כינוי.",
  claimed: "נקבע לך קוד אישי. מעכשיו נכנסים איתו.",
  timelineTitle: "סדר התאריכים",
  timeline: (lockDate: string, lockTime: string) => [
    { when: `עד ${lockDate} בשעה ${lockTime}`, what: "ממלאים הימור. אפשר לתקן כמה שרוצים." },
    { when: `${lockDate} בשעה ${lockTime}`, what: "הקלפיות נסגרות והטופס ננעל." },
    { when: "ליל הבחירות", what: "דירוג ביניים לפי המדגמים — לא סופי." },
    { when: "עם פרסום התוצאות הרשמיות", what: "חישוב ניקוד ודירוג סופי." },
  ],
  adminWrongCode: "הקוד לא נכון.",
  joinHint: "משתמש/ת ותיק/ה בלי קוד? הקלידו את השם שלכם ובחרו קוד — הוא יישמר לפעמים הבאות.",
  notYou: (name: string) => `לא ${name}?`,
  switchUser: "החלפת משתמש",
  joinNameMissing: "צריך שם, אפילו כינוי.",
  countdown: (d: number, h: number) => fill("הפתק נסגר בעוד {d} ימים {h} שעות", { d, h }),
  seatCounter: (n: number) => fill("מנדטים: {n}/120", { n }),
  sumOver: (n: number) => fill("יש לך {n} מנדטים. הכנסת מכילה 120. בבקשה תפריע/י פחות לדמוקרטיה.", { n }),
  sumUnder: (n: number) => fill("חסרים {n} מנדטים. הם לא יחלקו את עצמם.", { n }),
  submit: "סגור את הפתק",
  submitted: "ההימור נרשם. מעכשיו זה בידי העם.",
  edit: "תיקון אחרון",
  share: "שתפו בקבוצה",
  locked: "הקלפיות נסגרו. עכשיו רק מחכים.",
  boardBefore: "מה הקבוצה חושבת",
  exitPollLabel: "לפי מדגמים — לא סופי",
  pmOther: "מישהו אחר (כתבו מי)",
  pmOtherPlaceholder: "שם המועמד/ת",
  pmNone: "אין ממשלה — סיבוב נוסף",
  sectionSeats: "1. מנדטים",
  sectionPm: "2. ראש הממשלה",
  sectionBloc: "3. הגוש",
  sectionBlocHint: "מי יקים את הממשלה הבאה: גוש הקואליציה היוצאת או גוש האופוזיציה היוצאת?",
  sectionBonus: "4. בונוסים",
  blocCoalition: "קואליציה",
  blocOpposition: "אופוזיציה",
  yes: "כן",
  no: "לא",
  missingPm: "עוד לא בחרת ראש ממשלה.",
  missingBloc: "עוד לא בחרת גוש.",
  missingBonus: (n: number) => `נשארו ${n} שאלות בונוס בלי תשובה.`,
  genericError: "משהו השתבש. נסו שוב עוד רגע.",
  toBoard: "הקבוצות שלי",
  toBet: "להימור שלי",
  recruits: (n: number) => `${n} משתתפים הגישו`,
  avgSeats: "ממוצע מנדטים לכל מפלגה",
  pmDistribution: "מי יהיה ראש הממשלה, לפי הקבוצה",
  noBetsYet: "עוד אף אחד לא הגיש. תהיו הראשונים.",
  colPlace: "מקום",
  colName: "שם",
  colRank: "דרגה",
  colPoints: "נקודות",
  breakdown: (s: number, p: number, b: number, x: number) => `מנדטים ${s} · רה"מ ${p} · גוש ${b} · בונוס ${x}`,
  saving: "שולח…",
  downloading: "מכין תמונה…",
  shareCardFooter: "משחק על נקודות בלבד",
  shareCardPm: 'ראש הממשלה',
  shareCardTop3: "שלוש הגדולות",
  admin: {
    title: "חדר המצב",
    codeLabel: "קוד אדמין",
    enter: "כניסה",
    mode: "מצב תוצאות",
    modeNone: "אין תוצאות",
    modeExit: "מדגמים",
    modeOfficial: "רשמי",
    save: "שמור וחשב ניקוד",
    exportCsv: "ייצוא CSV",
    lock: "נעל טופס",
    unlock: "פתח טופס",
    autoLock: "חזרה לנעילה אוטומטית",
    saved: (n: number) => `נשמר, והניקוד חושב ל-${n} שחקנים.`,
    lockStatus: (locked: boolean, at: string) => `${locked ? "נעול" : "פתוח"} · נעילה: ${at}`,
    bonusUnknown: "עוד לא ידוע",
    tabResults: "תוצאות",
    tabPlayers: "שחקנים",
    playersTitle: (n: number, b: number) => `${n} שחקנים · ${b} הגישו`,
    search: "חיפוש לפי שם",
    submitted: "הגיש/ה",
    notSubmitted: "לא הגיש/ה",
    rename: "שינוי שם",
    saveName: "שמירה",
    cancel: "ביטול",
    resetBet: "איפוס",
    history: "היסטוריה",
    remove: "מחיקה",
    confirmReset: (name: string) => `לאפס את ההימור של ${name}? השחקן/ית יוכל/תוכל למלא מחדש (עד הנעילה).`,
    confirmRemove: (name: string) => `למחוק את ${name} לגמרי, כולל ההימור והניקוד? אי אפשר לבטל.`,
    nameTaken: "השם הזה כבר תפוס.",
    noPlayers: "עוד אין שחקנים.",
  },
};

export const TIERS = [
  { min: 181, name: "נביא/ת הקלפי" },
  { min: 151, name: "סוקר-על" },
  { min: 111, name: "מנהל קמפיין" },
  { min: 61, name: "יועץ אסטרטגי" },
  { min: 0, name: "פעיל שטח" },
];
